name = "the-scene-api"
main = "src/index.ts"
compatibility_date = "2024-03-01"

[vars]
ADMIN_EMAIL = "thejaswinps@gmail.com"

[[d1_databases]]
binding = "DB"
database_name = "the-scene-db"
database_id = "9edb8e04-364f-49c9-91b8-420c0ae7d915"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "the-scene-media"
